### ISSUE TITLE
Would you like to contribute my project ?

### ISSUE THREAD

**Issue by tlghn** [mscdex/httpolyglot#6]
Hi, I started a project called "Soprano" few weeks ago, And It would be great if you would like to contribute it. Or any valuable reviews would be great

Soprano is aiming to serve all protocols from same port (such as custom rpc, http, ftp). It is kind of generic abstract framework. It uses "awync" to avoid callback hell until async-await natively supported on nodejs. (Awync is async-await implementation of mine by using Javascript's Generator functions. Please see my repositories)

I am currently working on http protocol. 

Please find the project here [https://github.com/tlghn/soprano](https://github.com/tlghn/soprano)

Thanks in advance

**Comment by mscdex** [comment]
This project is more of a POC than anything really. It's nice to see that some people are actually using it for more than that though.

Extending support to other protocols can be a problem because of different (possibly broken) protocol implementations, even within the same protocol (for example ssh), which can cause issues when you're trying to differentiate between protocols that have different expectations. Not only that, but you'd then need to include/pick specific implementations to use (in node) for the other protocols, whereas this module only uses node core modules.

Good luck with your project, but I'm not really interested in extended support for other protocols. I am sure you will find others that have such an interest though.

**Comment by tlghn** [comment]
Thank you so much for your reviews.
